import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="w-full flex justify-between p-5 bg-white text-black z-10">
          <div className="flex gap-x-4">
            <div>Smart School</div>
            <Link href={"/orders"}>Orders</Link>
            <Link href={"/customers"}>Customers</Link>
          </div>
          <div className="flex gap-x-4">
            <div>Smart School2</div>
            <div>class21</div>
            <div>class22</div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
